import type { Metadata } from "next";
import { Noto_Sans_Georgian, Geist_Mono } from "next/font/google";
// import LocalFont from "next/font/local";
// import font from "../../public/font"
import "./globals.css";

const SansGeorgian = Noto_Sans_Georgian({
  variable: "--font-Noto-Sans-Georgian",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const helvetic = LocalFont({
//   src: [
//     {
//       path: '/font/HelveticaNeueMedium.otf',
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "/font/HelveticaNeueBold.otf",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-helvetic",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SansGeorgian.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
